const express = require('express');
const router = express.Router();
const adminController = require('../controllers/adminController');
router.delete('/delete-user/:id', adminController.removeUser);
router.post('/invite', adminController.sendInstructorInvite);
router.get('/instructors',adminController.getAllInstructors);
router.put('/update-role', adminController.changeUserRole);
router.get('/students', adminController.getStudents);
router.get('/classes', adminController.getAllClasses);
router.delete('/delete-class/:id', adminController.deleteClass);
router.get('/lesson-reports', adminController.getLessonReports);
router.put('/lesson-reports/:id/status', adminController.updateReportStatus);
router.delete('/delete-lesson/:id', adminController.deleteLesson);
router.get('/dashboard-stats', adminController.getDashboardData);
router.get('/categories', adminController.getCategories);
router.post('/categories', adminController.createCategory);
router.put('/categories/:id', adminController.updateCategory);
router.delete('/categories/:id', adminController.deleteCategory);
router.put('/update-class-status/:id', adminController.updateClassStatus);
module.exports = router;